#!/bin/sh

BASEDIR=entries
TMPDIR=tmp

STYLESHEET=/usr/share/web/xsl/yagsbook/html/yagsbook.xsl
STYLESHEET=/home/sam/cvs/rpg/yagsbook/xsl/html/encyclopedia.xsl

rm -fr $BASEDIR $TMPDIR

mkdir $BASEDIR $TMPDIR $TMPDIR/topics

#
# First of all, build the encyclopedia entries as HTML from the
# XML sources, placing them in the correct (letter) directory.
#
for letter in a b c d e f g h i j k l m n o p q r s t u v w x y z
do
    mkdir $BASEDIR/$letter
    find src -name "$letter*.yags" -print > $TMPDIR/$letter

    if [ -s $TMPDIR/$letter ]
    then
        echo "Processing $letter: "`wc -l $TMPDIR/$letter | awk '{ print $1}'`

        cat $TMPDIR/$letter | while read infile
        do
            htmlfile=`echo $infile | sed s/yags/html/`
            outfile=$BASEDIR/$letter/`basename $htmlfile`
            ./yags2html $infile $STYLESHEET $outfile

            title=`xsltproc xsl/title.xsl $infile | grep -v version`
            slugline=`xsltproc xsl/slugline.xsl $infile | grep -v version`

            link=`echo $outfile | sed "s/entries\///"`
            href="<a href=\"$link\">$title</a>, $slugline"
            echo $href >> $BASEDIR/$letter.html

            # Find all the topics this article is a member of,
            # and populate each topic list with this article's href.
            xsltproc xsl/topics.xsl $infile | grep -v version | \
                awk -F, '{for (i = 1; i < NF; i++) print $i }' > $TMPDIR/topicfile
            cat $TMPDIR/topicfile | while read topic
            do
                mkdir -p $TMPDIR/topics/$topic
                echo $href >> $TMPDIR/topics/$topic/$letter
            done
        done
    fi
done


#
# Now generate the index pages for everything.
#
for topic in $TMPDIR/topics/*
do
    MAINFILE=$TMPDIR/mainfile.html
    rm -f $MAINFILE
    for letter in a b c d e f g h i j k l m n o p q r s t u v w x y z
    do

        file=$topic/$letter

        if [ -s $file ]
        then
            number=`wc -l $file | awk '{ print $1}'`
            heading=`echo $letter | tr "a-z" "A-Z"`
            echo "<h2>$heading</h2>" >> $MAINFILE
            echo "<p>" >> $MAINFILE

            cat $file | while read entry
            do
                echo $entry >> $MAINFILE
                echo "<br/>" >> $MAINFILE
            done
            echo "</p>" >> $MAINFILE
        fi
    done
    topicfile=entries/`basename $topic | tr "A-Z" "a-z"`.html
    echo $topicfile

    if [ -s $MAINFILE ]
    then
        cat templates/index.html > $topicfile
        cat $MAINFILE >> $topicfile
        cat templates/footer.html >> $topicfile
    fi
done
